# Generated by Django 6.0 on 2026-03-24 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.FloatField()),
                ('algorithm_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_models', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lorawan.mlmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelTrainingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained_at', models.DateTimeField(null=True)),
                ('training_data_file', models.CharField(max_length=100)),
                ('num_training_samples', models.IntegerField()),
                ('contamination', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lorawan.mlmodel')),
                ('trained_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPredictionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('input_file_name', models.CharField(max_length=255)),
                ('num_packets', models.IntegerField()),
                ('anomalies_detected', models.IntegerField()),
                ('anomaly_percentage', models.FloatField()),
                ('silhouette_score', models.FloatField(blank=True, null=True)),
                ('mean_anomaly_score', models.FloatField()),
                ('std_anomaly_score', models.FloatField(blank=True, null=True)),
                ('min_anomaly_score', models.FloatField()),
                ('max_anomaly_score', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lorawan.mlmodel')),
                ('training_run_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lorawan.modeltraininginfo')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('mac', models.CharField(max_length=6)),
                ('spreading_factor', models.IntegerField()),
                ('channel_frequency', models.FloatField()),
                ('transmission_power', models.IntegerField()),
                ('bandwidth', models.IntegerField()),
                ('coding_rate', models.IntegerField()),
                ('snr', models.FloatField()),
                ('rssi', models.FloatField()),
                ('sequence_number', models.IntegerField()),
                ('payload', models.CharField(max_length=20)),
                ('payload_size', models.IntegerField()),
                ('num_recieved_per_node', models.IntegerField()),
                ('pdr_per_node', models.IntegerField()),
                ('num_recieved_per_node_per_window', models.IntegerField()),
                ('current_seq_num', models.IntegerField(default=0)),
                ('last_seq_num_at_window_start', models.IntegerField()),
                ('pdr_per_node_per_window', models.IntegerField()),
                ('inter_arrival_time_s', models.FloatField()),
                ('inter_arrival_time_m', models.FloatField()),
                ('is_anomalous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nodeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lorawan.node')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('log_type', models.CharField(choices=[('model_run', 'Model Run'), ('anomaly_detected', 'Anomaly Detected'), ('device_added', 'Device Added'), ('device_removed', 'Device Removed'), ('device_status_change', 'Device Status Change')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], default='info', max_length=20)),
                ('anomaly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lorawan.anomaly')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lorawan.node')),
                ('packet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lorawan.packet')),
            ],
        ),
        migrations.AddField(
            model_name='anomaly',
            name='packet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lorawan.packet'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('alert_type', models.CharField(choices=[('anomaly', 'Anomaly'), ('system', 'System')], default='system', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('anomaly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lorawan.anomaly')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lorawan.node')),
                ('packet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lorawan.packet')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
