# Generated by Django 6.0 on 2026-01-19 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Packets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('mac', models.CharField(max_length=6)),
                ('spreading_factor', models.IntegerField()),
                ('channel_frequency', models.CharField()),
                ('transmission_power', models.CharField()),
                ('bandwidth', models.CharField()),
                ('coding_rate', models.CharField()),
                ('snr', models.FloatField()),
                ('rssi', models.FloatField()),
                ('sequence_number', models.IntegerField()),
                ('payload', models.CharField()),
                ('payload_size', models.IntegerField()),
                ('num_recieved_per_node', models.CharField()),
                ('pdr_per_node', models.CharField()),
                ('num_recieved_per_node_per_window', models.CharField()),
                ('last_seq_num_at_window_start', models.CharField()),
                ('pdr_per_node_per_window', models.CharField()),
                ('inter_arrival_time_s', models.CharField()),
                ('inter_arrival_time_m', models.CharField()),
                ('interArrivalTimeM', models.CharField()),
                ('created_at', models.DateTimeField()),
                ('nodeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lorawan.nodes')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('origanisation', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
