# Generated by Django 6.0 on 2026-03-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
