# Generated by Django 6.0 on 2026-01-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packets',
            name='interArrivalTimeM',
        ),
        migrations.AlterField(
            model_name='packets',
            name='bandwidth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='packets',
            name='channel_frequency',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='packets',
            name='coding_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='packets',
            name='inter_arrival_time_m',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='packets',
            name='inter_arrival_time_s',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='packets',
            name='last_seq_num_at_window_start',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='packets',
            name='num_recieved_per_node',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='packets',
            name='num_recieved_per_node_per_window',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='packets',
            name='payload',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='packets',
            name='pdr_per_node',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='packets',
            name='pdr_per_node_per_window',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='packets',
            name='transmission_power',
            field=models.IntegerField(),
        ),
    ]
