# Generated by Django 6.0 on 2026-01-22 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('version', models.FloatField()),
                ('algorithm_type', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anomaly', models.BooleanField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lorawan.packet')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lorawan.mlmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='AnomalyDetection',
        ),
    ]
