# Generated by Django 6.0 on 2026-02-10 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomaly',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='anomaly',
            name='is_anomaly',
        ),
        migrations.CreateModel(
            name='ModelTrainingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained_at', models.DateTimeField(null=True)),
                ('training_data_file', models.CharField(max_length=100)),
                ('num_training_samples', models.IntegerField()),
                ('contamination', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lorawan.mlmodel')),
                ('trained_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPredictionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_at', models.DateField()),
                ('input_file_name', models.CharField()),
                ('num_packets', models.IntegerField()),
                ('anomalies_detected', models.IntegerField()),
                ('anomaly_percentage', models.FloatField()),
                ('mean_anomaly_score', models.FloatField()),
                ('min_anomaly_score', models.FloatField()),
                ('max_anomaly_score', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lorawan.mlmodel')),
                ('training_run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lorawan.modeltraininginfo')),
            ],
        ),
    ]
