# Generated by Django 6.0 on 2026-03-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0002_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='severity',
            field=models.CharField(choices=[('success', 'Success'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20),
        ),
    ]
