# Generated by Django 6.0 on 2026-02-11 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0002_remove_anomaly_confidence_remove_anomaly_is_anomaly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpredictioninfo',
            name='precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelpredictioninfo',
            name='silhouette_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelpredictioninfo',
            name='std_anomaly_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelpredictioninfo',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelpredictioninfo',
            name='f1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelpredictioninfo',
            name='input_file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='modelpredictioninfo',
            name='predicted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='modelpredictioninfo',
            name='recall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelpredictioninfo',
            name='training_run_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lorawan.modeltraininginfo'),
        ),
    ]
