# Generated by Django 6.0 on 2026-01-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0002_remove_packets_interarrivaltimem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
