# Generated by Django 6.0 on 2026-01-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0002_mlmodel_alter_node_owner_anomaly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
