# Generated by Django 6.0 on 2026-01-19 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0003_alter_nodes_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nodes',
            new_name='Node',
        ),
        migrations.RenameModel(
            old_name='Packets',
            new_name='Packet',
        ),
    ]
