# Generated by Django 6.0 on 2026-03-03 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0003_modelpredictioninfo_precision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('message', models.CharField()),
                ('alert_type', models.CharField()),
                ('severity', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateField()),
                ('anomaly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lorawan.anomaly')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lorawan.node')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('packet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lorawan.packet')),
            ],
        ),
    ]
