# Generated by Django 6.0 on 2026-01-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0003_alter_packet_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomaly',
            old_name='packet',
            new_name='packet_id',
        ),
    ]
