# Generated by Django 6.0 on 2026-01-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0004_rename_nodes_node_rename_packets_packet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
