# Generated by Django 6.0 on 2026-01-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0004_rename_packet_anomaly_packet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='current_seq_num',
            field=models.IntegerField(default=0),
        ),
    ]
