# Generated by Django 6.0 on 2026-03-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0004_alter_alert_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
