# Generated by Django 6.0 on 2026-03-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0004_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='resolved_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
