# Generated by Django 6.0 on 2026-03-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0005_alter_alert_resolved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('anomaly', 'Anomaly'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
