# Generated by Django 6.0 on 2026-01-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0005_packet_current_seq_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomaly',
            old_name='packet_id',
            new_name='packet',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='origanisation',
            new_name='organisation',
        ),
        migrations.AddField(
            model_name='anomaly',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packet',
            name='is_anomalous',
            field=models.BooleanField(default=False),
        ),
    ]
