# Generated by Django 6.0 on 2026-03-26 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0005_log_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='anomaly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lorawan.anomaly'),
        ),
    ]
