# Generated by Django 6.0 on 2026-04-05 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0006_alter_log_anomaly'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpredictioninfo',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelpredictioninfos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modeltraininginfo',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modeltraininginfos', to=settings.AUTH_USER_MODEL),
        ),
    ]
