# Generated by Django 6.0 on 2026-03-20 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0006_alter_alert_alert_type_alter_alert_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly', to=settings.AUTH_USER_MODEL),
        ),
    ]
