# Generated by Django 6.0 on 2026-01-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0006_rename_packet_id_anomaly_packet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
