# Generated by Django 6.0 on 2026-04-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0007_modelpredictioninfo_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeltraininginfo',
            name='trained_by_id',
        ),
    ]
