# Generated by Django 6.0 on 2026-04-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0009_packet_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='owner',
            new_name='created_by',
        ),
    ]
