# Generated by Django 6.0 on 2026-04-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0010_rename_owner_node_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomaly',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='mlmodel',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='modelpredictioninfo',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='modeltraininginfo',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='packet',
            old_name='created_by',
            new_name='owner',
        ),
    ]
