# Generated by Django 6.0 on 2026-04-05 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0011_rename_created_by_anomaly_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='detected_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
