# Generated by Django 6.0 on 2026-04-14 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0013_alert_is_resolved_alert_resolved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lorawan.mlmodel'),
        ),
    ]
