# Generated by Django 6.0 on 2026-04-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorawan', '0014_alert_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='latitiude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
